# Generated by Django 5.2.5 on 2025-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveBigIntegerField(unique=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('merkle_root', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=64)),
                ('mined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-height'],
                'indexes': [models.Index(fields=['height'], name='blocks_bloc_height_87307e_idx'), models.Index(fields=['mined_at'], name='blocks_bloc_mined_a_a59717_idx')],
            },
        ),
    ]
