# Generated by Django 5.2.5 on 2025-09-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('price_usd', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts'], name='priceticks__ts_9b40cc_idx')],
            },
        ),
    ]
