# Generated by Django 5.2.5 on 2025-09-17 06:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('tx_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blocks.block')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tx_as_sender', to='wallets.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tx_as_receiver', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'), models.Index(fields=['from_wallet'], name='transaction_from_wa_8257c5_idx'), models.Index(fields=['to_wallet'], name='transaction_to_wall_b17f16_idx')],
            },
        ),
    ]
