# Generated by Django 5.2.5 on 2025-09-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_trade_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='traderequest',
            new_name='transaction_status_677e82_idx',
            old_name='tx_req_status_idx',
        ),
        migrations.RenameIndex(
            model_name='traderequest',
            new_name='transaction_counter_1e5cc5_idx',
            old_name='tx_req_cpty_idx',
        ),
    ]
